---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-01-volume 
  namespace: development
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "redis-pv1"
    readOnly: false
#  storageClassName: glusterfs-redis-01

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-02-volume
  namespace: development
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "redis-pv2"
    readOnly: false
#  storageClassName: glusterfs-redis-02

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-03-volume
  namespace: development
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "redis-pv3"
    readOnly: false
#  storageClassName: glusterfs-redis-03

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-04-volume
  namespace: development
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "redis-pv4"
    readOnly: false
#  storageClassName: glusterfs-redis-04

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-05-volume
  namespace: development
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "redis-pv5"
    readOnly: false
#  storageClassName: glusterfs-redis-05

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-06-volume
  namespace: development
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "redis-pv6"
    readOnly: false
#  storageClassName: glusterfs-redis-06





