apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  labels:
    app: kafka
  namespace: development
spec:
  ports:
  - port: 9092
    name: server
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  labels:
    app: kafka
  namespace: development
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
  namespace: development
spec:
  selector:
    matchLabels:
      app: kafka
  minAvailable: 2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  namespace: development
spec:
  serviceName: kafka-server
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: dochub.com/wurstmeister/kafka
        readinessProbe:
          tcpSocket:
            port: 9092
          #exec:
          #  command:
          #  - sh
          #  - -c
          #  - "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server=localhost:9092"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9092
          #exec:
          #  command:
          #  - sh
          #  - -c
          #  - "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server=localhost:9092"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - containerPort: 9093
          name: server
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          #value: "zk-cs:2181"
          value: "zk-0.zk-hs.development.svc.cluster.local:2181,zk-1.zk-hs.development.svc.cluster.local:2181,zk-2.zk-hs.development.svc.cluster.local:2181"
        - name: KAFKA_HEAP_OPTS
          value : "-Xmx512M -Xms512M"
        - name: KAFKA_OPTS
          value: "-Dlogging.level=INFO"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: BROKER_ID_COMMAND
          value: "hostname | awk -F'-' '{print $2}'"
        - name: TZ
          value: Asia/Hong_Kong
        resources:
          limits:
            cpu: 500m
            memory: 6Gi
          requests:
            memory: "2Gi"
            cpu: 200m
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/kafka
      imagePullSecrets:
      - name: registrykey
      #securityContext:
      #  runAsUser: 1000
      #  fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.beta.kubernetes.io/storage-class: "kafka-sc"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rbd
      resources:
        requests:
          storage: 2Gi